# Generated by Django 4.1.4 on 2022-12-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyahat_agency_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagemodel',
            name='destination',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='about_us',
            field=models.TextField(max_length=500),
        ),
    ]
